// Class to hold beverage information.
// e.g., "Coffee has 0.38mg of caffeine per oz and a hydration factor of 0.75."
// fromMap: DB -> Dart Object
// toMap: Dart Object -> DB

class Beverage {
  final int? id;                // Unique beverage ID (auto-generated by DB)
  final String name;            // Beverage name (e.g., "Coffee")
  final double caffeinePerOz;   // Caffeine content per oz (mg)
  final double hydrationFactor; // Hydration factor (0.0 to 1.0)
  final int defaultVolumeOz;    // Default volume in ounces (oz)

  Beverage({
    this.id,
    required this.name,
    required this.caffeinePerOz,
    required this.hydrationFactor,
    required this.defaultVolumeOz,
  });

  /// Converts a Map (from the DB) into a Beverage object.
  /// e.g.: {'id': 1, 'name': 'Coffee', 'caffeine_per_oz': 0.38, 'hydration_factor': 0.75, 'default_volume_oz': 12}
  factory Beverage.fromMap(Map<String, dynamic> map) {
    return Beverage(
      id: map['id'] as int?,
      name: map['name'] as String,
      caffeinePerOz: map['caffeine_per_oz'] as double,
      hydrationFactor: map['hydration_factor'] as double,
      defaultVolumeOz: map['default_volume_oz'] as int,
    );
  }

  /// Converts the Beverage object into a Map suitable for DB storage.
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'caffeine_per_oz': caffeinePerOz,
      'hydration_factor': hydrationFactor,
      'default_volume_oz': defaultVolumeOz,
    };
  }
}