// Class to hold beverage information.
// e.g., "Coffee has 0.38mg of caffeine per oz and a hydration factor of 0.75."
// fromMap: DB -> Dart Object
// toMap: Dart Object -> DB

class Beverage {
  final int? id;                // Unique beverage ID (auto-generated by DB)
  final String name;            // Beverage name (e.g., "Coffee")
  final double caffeinePerOz;   // Caffeine content per oz (mg)
  final double hydrationFactor; // Hydration factor (0.0 to 1.0)
  final int defaultVolumeOz;    // Default volume in ounces (oz)
  final bool isAlcoholic;
  final double? abv;
  final double? servingSizeOz;

  Beverage({
    this.id,
    required this.name,
    required this.caffeinePerOz,
    required this.hydrationFactor,
    required this.defaultVolumeOz,
    this.isAlcoholic = false,
    this.abv,
    this.servingSizeOz,
  });

  factory Beverage.fromMap(Map<String, dynamic> map) {
    return Beverage(
      id: map['id'] as int?,
      name: map['name'] as String,
      caffeinePerOz: (map['caffeine_per_oz'] as num).toDouble(),
      hydrationFactor: (map['hydration_factor'] as num).toDouble(),
      defaultVolumeOz: (map['default_volume_oz'] as num).toInt(),
      isAlcoholic: map['is_alcoholic'] as bool? ?? false,
      abv: (map['abv'] as num?)?.toDouble(),
      servingSizeOz: (map['serving_size_oz'] as num?)?.toDouble(),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'caffeine_per_oz': caffeinePerOz,
      'hydration_factor': hydrationFactor,
      'default_volume_oz': defaultVolumeOz,
      'is_alcoholic': isAlcoholic,
      'abv': abv,
      'serving_size_oz': servingSizeOz,
    };
  }

  double standardDrinks({double? volumeOz}) {
    if (!isAlcoholic || abv == null) return 0.0;
    final vol = volumeOz ?? defaultVolumeOz.toDouble();
    return (vol * (abv! / 100)) / 0.6;
  }
}
